### PR TITLE
Display Alert to Set Own API Key

### LINKED ISSUE #9: Display Alert to set their own API key
Since the default API key supports only 10 requests per minute. A popup/alert can be displayed in the home page, that tells the users to add their own API key by clicking the settings tab.

If this is something you want to implement ??? then i can work on it !!!!

### PR DESCRIPTION
**Pull request by manas-2003**
Made the changes as specified by you in the issue #9 

Closes #9

### CODE REVIEW

**Comment by chinesedfan** [comment]
Good! Let's remove unnecessary changes to yarn.lock and package-lock.json. Only 1 file should be changed.

**Comment by manas-2003** [comment]
I removed package-lock and updated yarn.lock with the original file. Can you please review it once.

**Comment by chinesedfan** [comment]
> Only 1 file should be changed.

Now yarn.lock is not exactly the same. Please update again.

**Comment by manas-2003** [comment]
Yeah that's the issue. I'm trying to update it with the exact code in github but I don't know why it shows that I made changes in yarn.lock . But when i compare both of them in the Files changed tab, it looks same.

Can you help me out !!!!

**Comment by chinesedfan** [comment]
You should end the file with a newline. The easiest way is pressing the ENTER key. :)

BTW, I want to share some git tips. `git checkout master -- file1 file2` can revert changes to specified git branches.

**Comment by manas-2003** [comment]
Yeah my bad that I didn't notice the new line. And thank you for responding patiently. I have updated the changes can you review now please.

**Pull request merged**
